name: Automerge MAIN TO SIT

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '* * * * *'

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://tomekind92:${{secrets.GITHUB_TOKEN}}@github.com/tomekind92/LWCComponents.git

  # branch to be merged
  MY_BRANCH: sit

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/tomekind92/LWCComponents.git

  # replace "main" with your master branch name
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with main
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
